<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    
    public function run()
    {
        
$cities = array(
  array('id' => '1','name' => 'Aba North','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '2','name' => 'Aba South','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '3','name' => 'Arochukwu','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '4','name' => 'Bende','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '5','name' => 'Ikwuano','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '6','name' => 'Isiala Ngwa North','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '7','name' => 'Isiala Ngwa South','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '8','name' => 'Isuikwuato','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '9','name' => 'Obi Ngwa','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '10','name' => 'Ohafia','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '11','name' => 'Osisioma','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '12','name' => 'Ugwunagbo','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '13','name' => 'Ukwa East','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '14','name' => 'Ukwa West','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '15','name' => 'Umuahia North','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '16','name' => 'Umuahia South','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '17','name' => 'Umu Nneochi','code' => '','state_id' => '1','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '18','name' => 'Demsa','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '19','name' => 'Fufure','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '20','name' => 'Ganye','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '21','name' => 'Gayuk','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '22','name' => 'Gombi','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '23','name' => 'Gerfi','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '24','name' => 'Hong','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '25','name' => 'Jada','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '26','name' => 'Larmurde','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '27','name' => 'Madagali','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '28','name' => 'Maiha','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '29','name' => 'Mayo Belwa','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '30','name' => 'Michika','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '31','name' => 'Mubi North','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '32','name' => 'Mubi South','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '33','name' => 'Numan','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '34','name' => 'Shelleng','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '35','name' => 'Song','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '36','name' => 'Toungo','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '37','name' => 'Yola North','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '38','name' => 'Yola South','code' => '','state_id' => '2','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '39','name' => 'Abak','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '40','name' => 'Eastern Obolo','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '41','name' => 'Eket','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '42','name' => 'Esit Eket','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '43','name' => 'Essien Udim','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '44','name' => 'Etim Ekpo','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '45','name' => 'Etinan','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '46','name' => 'Ibeno','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '47','name' => 'Ibesikpo Asutan','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '48','name' => 'Ibiono-Ibom','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '49','name' => 'Ika','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '50','name' => 'Ikono','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '51','name' => 'Ikot Abasi','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '52','name' => 'Ikot Ekpene','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '53','name' => 'Ini','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '54','name' => 'Itu','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '55','name' => 'Mbo','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '56','name' => 'Mkpat-Enin','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '57','name' => 'Nsit-Atai','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '58','name' => 'Nsit-Ibom','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '59','name' => 'Nsit-Ubium','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '60','name' => 'Obot Akara','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '61','name' => 'Okobo','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '62','name' => 'Onna','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '63','name' => 'Oron','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '64','name' => 'Oruk Anam','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '65','name' => 'Udung-Uko','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '66','name' => 'Ukanafun','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '67','name' => 'Uruan','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '68','name' => 'Urue-Offong/Oruko','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '69','name' => 'Uyo','code' => '','state_id' => '3','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '70','name' => 'Aguata','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '71','name' => 'Anambra East','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '72','name' => 'Anambra West','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '73','name' => 'Anaocha','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '74','name' => 'Awka North','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '75','name' => 'Awka South','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '76','name' => 'Ayamelum','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '77','name' => 'Dunukofia','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '78','name' => 'Ekwusigo','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '79','name' => 'Idemili North','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '80','name' => 'Idemili South','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '81','name' => 'Ihiala','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '82','name' => 'Njikoka','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '83','name' => 'Nnewi North','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '84','name' => 'Nnewi South','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '85','name' => 'Ogbaru','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '86','name' => 'Onitsha North','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '87','name' => 'Onitsha South','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '88','name' => 'Orumba North','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '89','name' => 'Orumba South','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '90','name' => 'Oyi','code' => '','state_id' => '4','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '91','name' => 'Alkaleri','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '92','name' => 'Bauchi','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '93','name' => 'Bogoro','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '94','name' => 'Damban','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '95','name' => 'Darazo','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '96','name' => 'Dass','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '97','name' => 'Gamawa','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '98','name' => 'Ganjuwa','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '99','name' => 'Giade','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '100','name' => 'Itas/Gadau','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '101','name' => 'Jama\'are','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '102','name' => 'Katagum','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '103','name' => 'Kirfi','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '104','name' => 'Misau','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '105','name' => 'Ningi','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '106','name' => 'Shira','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '107','name' => 'Tafawa Balewa','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '108','name' => 'Toro','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '109','name' => 'Warji','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '110','name' => 'Zaki','code' => '','state_id' => '5','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '111','name' => 'Brass','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '112','name' => 'Ekeremor','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '113','name' => 'Kolokuma/Opokuma','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '114','name' => 'Nembe','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '115','name' => 'Ogbia','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '116','name' => 'Sagbama','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '117','name' => 'Southern Ijaw','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '118','name' => 'Yenagoa','code' => '','state_id' => '6','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '119','name' => 'Agatu','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '120','name' => 'Apa','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '121','name' => 'Ado','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '122','name' => 'Buruku','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '123','name' => 'Gboko','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '124','name' => 'Guma','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '125','name' => 'Gwer East','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '126','name' => 'Gwer West','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '127','name' => 'Katsina-Ala','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '128','name' => 'Konshisha','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '129','name' => 'Kwande','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '130','name' => 'Logo','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '131','name' => 'Makurdi','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '132','name' => 'Obi','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '133','name' => 'Ogbadibo','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '134','name' => 'Ohimini','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '135','name' => 'Oju','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '136','name' => 'Okpokwu','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '137','name' => 'Oturkpo','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '138','name' => 'Tarka','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '139','name' => 'Ukum','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '140','name' => 'Ushongo','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '141','name' => 'Vandeikya','code' => '','state_id' => '7','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '142','name' => 'Abadam','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '143','name' => 'Askira/Uba','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '144','name' => 'Bama','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '145','name' => 'Bayo','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '146','name' => 'Biu','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '147','name' => 'Chibok','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '148','name' => 'Damboa','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '149','name' => 'Dikwa','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '150','name' => 'Gubio','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '151','name' => 'Guzamala','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '152','name' => 'Gwoza','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '153','name' => 'Hawul','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '154','name' => 'Jere','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '155','name' => 'Kaga','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '156','name' => 'Kala/Balge','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '157','name' => 'Konduga','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '158','name' => 'Kukawa','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '159','name' => 'Kwaya Kusar','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '160','name' => 'Mafa','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '161','name' => 'Magumeri','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '162','name' => 'Maiduguri','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '163','name' => 'Marte','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '164','name' => 'Mobbar','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '165','name' => 'Monguno','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '166','name' => 'Ngala','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '167','name' => 'Nganzai','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '168','name' => 'Shani','code' => '','state_id' => '8','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '169','name' => 'Abi','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '170','name' => 'Akamkpa','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '171','name' => 'Akpabuyo','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '172','name' => 'Bakassi','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '173','name' => 'Bekwarra','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '174','name' => 'Biase','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '175','name' => 'Boki','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '176','name' => 'Calabar Municipal','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '177','name' => 'Calabar South','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '178','name' => 'Etung','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '179','name' => 'Ikom','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '180','name' => 'Obanliku','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '181','name' => 'Obubra','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '182','name' => 'Obudu','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '183','name' => 'Odukpani','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '184','name' => 'Ogoja','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '185','name' => 'Yakuur','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '186','name' => 'Yala','code' => '','state_id' => '9','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '187','name' => 'Aniocha North','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '188','name' => 'Aniocha South','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '189','name' => 'Bomadi','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '190','name' => 'Burutu','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '191','name' => 'Ethiope East','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '192','name' => 'Ethiope West','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '193','name' => 'Ika North East','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '194','name' => 'Ika South','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '195','name' => 'Isoko North','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '196','name' => 'Isoko South','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '197','name' => 'Ndokwa East','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '198','name' => 'Ndokwa West','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '199','name' => 'Okpe','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '200','name' => 'Oshimili North','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '201','name' => 'Oshimili South','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '202','name' => 'Patani','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '203','name' => 'Sapele, Delta','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '204','name' => 'Udu','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '205','name' => 'Ughelli North','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '206','name' => 'Ughelli South','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '207','name' => 'Ukwuani','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '208','name' => 'Uvwie','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '209','name' => 'Warri North','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '210','name' => 'Warri South','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '211','name' => 'Warri South West','code' => '','state_id' => '10','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '212','name' => 'Abakaliki','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '213','name' => 'Afikpo North','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '214','name' => 'Afikpo South','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '215','name' => 'Ebonyi','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '216','name' => 'Ezza North','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '217','name' => 'Ezza South','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '218','name' => 'Ikwo','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '219','name' => 'Ishielu','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '220','name' => 'Ivo','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '221','name' => 'Izzi','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '222','name' => 'Ohaozara','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '223','name' => 'Ohaukwu','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '224','name' => 'Onicha','code' => '','state_id' => '11','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '225','name' => 'Akoko-Edo','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '226','name' => 'Egor','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '227','name' => 'Esan Central','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '228','name' => 'Esan North-East','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '229','name' => 'Esan South-East','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '230','name' => 'Esan West','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '231','name' => 'Etsako Central','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '232','name' => 'Etsako East','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '233','name' => 'Etsako West','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '234','name' => 'Igueben','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '235','name' => 'Ikpoba Okha','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '236','name' => 'Orhionmwon','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '237','name' => 'Oredo','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '238','name' => 'Ovia North-East','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '239','name' => 'Ovia South-West','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '240','name' => 'Owan East','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '241','name' => 'Owan West','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '242','name' => 'Uhunmwonde','code' => '','state_id' => '12','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '243','name' => 'Ado Ekiti','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '244','name' => 'Efon','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '245','name' => 'Ekiti East','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '246','name' => 'Ekiti South-West','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '247','name' => 'Ekiti West','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '248','name' => 'Emure','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '249','name' => 'Gbonyin','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '250','name' => 'Ido Osi','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '251','name' => 'Ijero','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '252','name' => 'Ikere','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '253','name' => 'Ikole','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '254','name' => 'Ilejemeje','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '255','name' => 'Irepodun/Ifelodun','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '256','name' => 'Ise/Orun','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '257','name' => 'Moba','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '258','name' => 'Oye','code' => '','state_id' => '13','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '259','name' => 'Aninri','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '260','name' => 'Awgu','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '261','name' => 'Enugu East','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '262','name' => 'Enugu North','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '263','name' => 'Enugu South','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '264','name' => 'Ezeagu','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '265','name' => 'Igbo Etiti','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '266','name' => 'Igbo Eze North','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '267','name' => 'Igbo Eze South','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '268','name' => 'Isi Uzo','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '269','name' => 'Nkanu East','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '270','name' => 'Nkanu West','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '271','name' => 'Nsukka','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '272','name' => 'Oji River','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '273','name' => 'Udenu','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '274','name' => 'Udi','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '275','name' => 'Uzo Uwani','code' => '','state_id' => '14','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '276','name' => 'Abaji','code' => '','state_id' => '15','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '277','name' => 'Bwari','code' => '','state_id' => '15','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '278','name' => 'Gwagwalada','code' => '','state_id' => '15','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '279','name' => 'Kuje','code' => '','state_id' => '15','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '280','name' => 'Kwali','code' => '','state_id' => '15','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '281','name' => 'Municipal Area Council','code' => '','state_id' => '15','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '282','name' => 'Akko','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '283','name' => 'Balanga','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '284','name' => 'Billiri','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '285','name' => 'Dukku','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '286','name' => 'Funakaye','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '287','name' => 'Gombe','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '288','name' => 'Kaltungo','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '289','name' => 'Kwami','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '290','name' => 'Nafada','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '291','name' => 'Shongom','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '292','name' => 'Yamaltu/Deba','code' => '','state_id' => '16','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '293','name' => 'Aboh Mbaise','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '294','name' => 'Ahiazu Mbaise','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '295','name' => 'Ehime Mbano','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '296','name' => 'Ezinihitte','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '297','name' => 'Ideato North','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '298','name' => 'Ideato South','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '299','name' => 'Ihitte/Uboma','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '300','name' => 'Ikeduru','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '301','name' => 'Isiala Mbano','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '302','name' => 'Isu','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '303','name' => 'Mbaitoli','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '304','name' => 'Ngor Okpala','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '305','name' => 'Njaba','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '306','name' => 'Nkwerre','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '307','name' => 'Nwangele','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '308','name' => 'Obowo','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '309','name' => 'Oguta','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '310','name' => 'Ohaji/Egbema','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '311','name' => 'Okigwe','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '312','name' => 'Orlu','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '313','name' => 'Orsu','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '314','name' => 'Oru East','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '315','name' => 'Oru West','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '316','name' => 'Owerri Municipal','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '317','name' => 'Owerri North','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '318','name' => 'Owerri West','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '319','name' => 'Unuimo','code' => '','state_id' => '17','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '320','name' => 'Auyo','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '321','name' => 'Babura','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '322','name' => 'Biriniwa','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '323','name' => 'Birnin Kudu','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '324','name' => 'Buji','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '325','name' => 'Dutse','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '326','name' => 'Gagarawa','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '327','name' => 'Garki','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '328','name' => 'Gumel','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '329','name' => 'Guri','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '330','name' => 'Gwaram','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '331','name' => 'Gwiwa','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '332','name' => 'Hadejia','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '333','name' => 'Jahun','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '334','name' => 'Kafin Hausa','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '335','name' => 'Kazaure','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '336','name' => 'Kiri Kasama','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '337','name' => 'Kiyawa','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '338','name' => 'Kaugama','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '339','name' => 'Maigatari','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '340','name' => 'Malam Madori','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '341','name' => 'Miga','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '342','name' => 'Ringim','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '343','name' => 'Roni','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '344','name' => 'Sule Tankarkar','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '345','name' => 'Taura','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '346','name' => 'Yankwashi','code' => '','state_id' => '18','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '347','name' => 'Birnin Gwari','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '348','name' => 'Chikun','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '349','name' => 'Giwa','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '350','name' => 'Igabi','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '351','name' => 'Ikara','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '352','name' => 'Jaba','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '353','name' => 'Jema\'a','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '354','name' => 'Kachia','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '355','name' => 'Kaduna North','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '356','name' => 'Kaduna South','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '357','name' => 'Kagarko','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '358','name' => 'Kajuru','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '359','name' => 'Kaura','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '360','name' => 'Kauru','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '361','name' => 'Kubau','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '362','name' => 'Kudan','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '363','name' => 'Lere','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '364','name' => 'Makarfi','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '365','name' => 'Sabon Gari','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '366','name' => 'Sanga','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '367','name' => 'Soba','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '368','name' => 'Zangon Kataf','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '369','name' => 'Zaria','code' => '','state_id' => '19','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '370','name' => 'Ajingi','code' => 'AJG','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '371','name' => 'Albasu','code' => 'ALB','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '372','name' => 'Bagwai','code' => 'BGW','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '373','name' => 'Bebeji','code' => 'BBJ','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '374','name' => 'Bichi','code' => 'BCH','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '375','name' => 'Bunkure','code' => 'BKR','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '376','name' => 'Dala','code' => 'DAL','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '377','name' => 'Dambatta','code' => 'DBT','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '378','name' => 'Dawakin Kudu','code' => 'DKD','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '379','name' => 'Dawakin Tofa','code' => 'DTF','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '380','name' => 'Doguwa','code' => 'DGW','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '381','name' => 'Fagge','code' => 'FGE','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '382','name' => 'Gabasawa','code' => 'GBS','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '383','name' => 'Garko','code' => 'GRK','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '384','name' => 'Garun Mallam','code' => 'GRM','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '385','name' => 'Gaya','code' => 'GYA','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '386','name' => 'Gezawa','code' => 'GZW','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '387','name' => 'Gwale','code' => 'GWL','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '388','name' => 'Gwarzo','code' => 'GWZ','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '389','name' => 'Kabo','code' => 'KAB','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '390','name' => 'Kano Municipal','code' => 'KMC','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '391','name' => 'Karaye','code' => 'KRY','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '392','name' => 'Kibiya','code' => 'KBY','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '393','name' => 'Kiru','code' => 'KRU','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '394','name' => 'Kumbotso','code' => 'KBT','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '395','name' => 'Kunchi','code' => 'KNC','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '396','name' => 'Kura','code' => 'KUR','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '397','name' => 'Madobi','code' => 'MDB','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '398','name' => 'Makoda','code' => 'MKD','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '399','name' => 'Minjibir','code' => 'MJB','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '400','name' => 'Nasarawa','code' => 'NSR','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '401','name' => 'Rano','code' => 'RAN','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '402','name' => 'Rimin Gado','code' => 'RMG','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '403','name' => 'Rogo','code' => 'RGG','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '404','name' => 'Shanono','code' => 'SNN','state_id' => '20','state_zone_id' => '5','code_pattern' => ''),
  array('id' => '405','name' => 'Sumaila','code' => 'SML','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '406','name' => 'Takai','code' => 'TKA','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '407','name' => 'Tarauni','code' => 'TRN','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '408','name' => 'Tofa','code' => 'TFA','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '409','name' => 'Tsanyawa','code' => 'TSW','state_id' => '20','state_zone_id' => '2','code_pattern' => ''),
  array('id' => '410','name' => 'Tudun Wada','code' => 'TWD','state_id' => '20','state_zone_id' => '4','code_pattern' => ''),
  array('id' => '411','name' => 'Ungogo','code' => 'UGG','state_id' => '20','state_zone_id' => '1','code_pattern' => ''),
  array('id' => '412','name' => 'Warawa','code' => 'WRW','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '413','name' => 'Wudil','code' => 'WDL','state_id' => '20','state_zone_id' => '3','code_pattern' => ''),
  array('id' => '414','name' => 'Bakori','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '415','name' => 'Batagarawa','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '416','name' => 'Batsari','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '417','name' => 'Baure','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '418','name' => 'Bindawa','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '419','name' => 'Charanchi','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '420','name' => 'Dandume','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '421','name' => 'Danja','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '422','name' => 'Dan Musa','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '423','name' => 'Daura','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '424','name' => 'Dutsi','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '425','name' => 'Dutsin Ma','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '426','name' => 'Faskari','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '427','name' => 'Funtua','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '428','name' => 'Ingawa','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '429','name' => 'Jibia','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '430','name' => 'Kafur','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '431','name' => 'Kaita','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '432','name' => 'Kankara','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '433','name' => 'Kankia','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '434','name' => 'Katsina','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '435','name' => 'Kurfi','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '436','name' => 'Kusada','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '437','name' => 'Mai\'Adua','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '438','name' => 'Malumfashi','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '439','name' => 'Mani','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '440','name' => 'Mashi','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '441','name' => 'Matazu','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '442','name' => 'Musawa','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '443','name' => 'Rimi','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '444','name' => 'Sabuwa','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '445','name' => 'Safana','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '446','name' => 'Sandamu','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '447','name' => 'Zango','code' => '','state_id' => '21','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '448','name' => 'Aleiro','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '449','name' => 'Arewa Dandi','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '450','name' => 'Argungu','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '451','name' => 'Augie','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '452','name' => 'Bagudo','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '453','name' => 'Birnin Kebbi','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '454','name' => 'Bunza','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '455','name' => 'Dandi','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '456','name' => 'Fakai','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '457','name' => 'Gwandu','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '458','name' => 'Jega','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '459','name' => 'Kalgo','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '460','name' => 'Koko/Besse','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '461','name' => 'Maiyama','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '462','name' => 'Ngaski','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '463','name' => 'Sakaba','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '464','name' => 'Shanga','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '465','name' => 'Suru','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '466','name' => 'Wasagu/Danko','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '467','name' => 'Yauri','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '468','name' => 'Zuru','code' => '','state_id' => '22','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '469','name' => 'Adavi','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '470','name' => 'Ajaokuta','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '471','name' => 'Ankpa','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '472','name' => 'Bassa','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '473','name' => 'Dekina','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '474','name' => 'Ibaji','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '475','name' => 'Idah','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '476','name' => 'Igalamela Odolu','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '477','name' => 'Ijumu','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '478','name' => 'Kabba/Bunu','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '479','name' => 'Kogi','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '480','name' => 'Lokoja','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '481','name' => 'Mopa Muro','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '482','name' => 'Ofu','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '483','name' => 'Ogori/Magongo','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '484','name' => 'Okehi','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '485','name' => 'Okene','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '486','name' => 'Olamaboro','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '487','name' => 'Omala','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '488','name' => 'Yagba East','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '489','name' => 'Yagba West','code' => '','state_id' => '23','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '490','name' => 'Asa','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '491','name' => 'Baruten','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '492','name' => 'Edu','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '493','name' => 'Ekiti, Kwara State','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '494','name' => 'Ifelodun','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '495','name' => 'Ilorin East','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '496','name' => 'Ilorin South','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '497','name' => 'Ilorin West','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '498','name' => 'Irepodun','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '499','name' => 'Isin','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '500','name' => 'Kaiama','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '501','name' => 'Moro','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '502','name' => 'Offa','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '503','name' => 'Oke Ero','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '504','name' => 'Oyun','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '505','name' => 'Pategi','code' => '','state_id' => '24','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '506','name' => 'Agege','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '507','name' => 'Ajeromi-Ifelodun','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '508','name' => 'Alimosho','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '509','name' => 'Amuwo-Odofin','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '510','name' => 'Apapa','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '511','name' => 'Badagry','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '512','name' => 'Epe','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '513','name' => 'Eti Osa','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '514','name' => 'Ibeju-Lekki','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '515','name' => 'Ifako-Ijaiye','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '516','name' => 'Ikeja','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '517','name' => 'Ikorodu','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '518','name' => 'Kosofe','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '519','name' => 'Lagos Island','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '520','name' => 'Lagos Mainland','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '521','name' => 'Mushin','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '522','name' => 'Ojo','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '523','name' => 'Oshodi-Isolo','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '524','name' => 'Shomolu','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '525','name' => 'Surulere, Lagos State','code' => '','state_id' => '25','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '526','name' => 'Akwanga','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '527','name' => 'Awe','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '528','name' => 'Doma','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '529','name' => 'Karu','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '530','name' => 'Keana','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '531','name' => 'Keffi','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '532','name' => 'Kokona','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '533','name' => 'Lafia','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '534','name' => 'Nasarawa','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '535','name' => 'Nasarawa Egon','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '536','name' => 'Obi','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '537','name' => 'Toto','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '538','name' => 'Wamba','code' => '','state_id' => '26','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '539','name' => 'Agaie','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '540','name' => 'Agwara','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '541','name' => 'Bida','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '542','name' => 'Borgu','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '543','name' => 'Bosso','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '544','name' => 'Chanchaga','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '545','name' => 'Edati','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '546','name' => 'Gbako','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '547','name' => 'Gurara','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '548','name' => 'Katcha','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '549','name' => 'Kontagora','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '550','name' => 'Lapai','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '551','name' => 'Lavun','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '552','name' => 'Magama','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '553','name' => 'Mariga','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '554','name' => 'Mashegu','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '555','name' => 'Mokwa','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '556','name' => 'Moya','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '557','name' => 'Paikoro','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '558','name' => 'Rafi','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '559','name' => 'Rijau','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '560','name' => 'Shiroro','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '561','name' => 'Suleja','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '562','name' => 'Tafa','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '563','name' => 'Wushishi','code' => '','state_id' => '27','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '564','name' => 'Abeokuta North','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '565','name' => 'Abeokuta South','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '566','name' => 'Ado-Odo/Ota','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '567','name' => 'Egbado North','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '568','name' => 'Egbado South','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '569','name' => 'Ewekoro','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '570','name' => 'Ifo','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '571','name' => 'Ijebu East','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '572','name' => 'Ijebu North','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '573','name' => 'Ijebu North East','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '574','name' => 'Ijebu Ode','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '575','name' => 'Ikenne','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '576','name' => 'Imeko Afon','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '577','name' => 'Ipokia','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '578','name' => 'Obafemi Owode','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '579','name' => 'Odeda','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '580','name' => 'Odogbolu','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '581','name' => 'Ogun Waterside','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '582','name' => 'Remo North','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '583','name' => 'Shagamu','code' => '','state_id' => '28','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '584','name' => 'Akoko North-East','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '585','name' => 'Akoko North-West','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '586','name' => 'Akoko South-West','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '587','name' => 'Akoko South-East','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '588','name' => 'Akure North','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '589','name' => 'Akure South','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '590','name' => 'Ese Odo','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '591','name' => 'Idanre','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '592','name' => 'Ifedore','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '593','name' => 'Ilaje','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '594','name' => 'Ile Oluji/Okeigbo','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '595','name' => 'Irele','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '596','name' => 'Odigbo','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '597','name' => 'Okitipupa','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '598','name' => 'Ondo East','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '599','name' => 'Ondo West','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '600','name' => 'Ose','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '601','name' => 'Owo','code' => '','state_id' => '29','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '602','name' => 'Atakunmosa East','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '603','name' => 'Atakunmosa West','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '604','name' => 'Aiyedaade','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '605','name' => 'Aiyedire','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '606','name' => 'Boluwaduro','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '607','name' => 'Boripe','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '608','name' => 'Ede North','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '609','name' => 'Ede South','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '610','name' => 'Ife Central','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '611','name' => 'Ife East','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '612','name' => 'Ife North','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '613','name' => 'Ife South','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '614','name' => 'Egbedore','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '615','name' => 'Ejigbo','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '616','name' => 'Ifedayo','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '617','name' => 'Ifelodun','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '618','name' => 'Ila','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '619','name' => 'Ilesa East','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '620','name' => 'Ilesa West','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '621','name' => 'Irepodun','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '622','name' => 'Irewole','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '623','name' => 'Isokan','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '624','name' => 'Iwo','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '625','name' => 'Obokun','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '626','name' => 'Odo Otin','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '627','name' => 'Ola Oluwa','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '628','name' => 'Olorunda','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '629','name' => 'Oriade','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '630','name' => 'Orolu','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '631','name' => 'Osogbo','code' => '','state_id' => '30','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '632','name' => 'Afijio','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '633','name' => 'Akinyele','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '634','name' => 'Atiba','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '635','name' => 'Atisbo','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '636','name' => 'Egbeda','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '637','name' => 'Ibadan North','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '638','name' => 'Ibadan North-East','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '639','name' => 'Ibadan North-West','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '640','name' => 'Ibadan South-East','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '641','name' => 'Ibadan South-West','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '642','name' => 'Ibarapa Central','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '643','name' => 'Ibarapa East','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '644','name' => 'Ibarapa North','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '645','name' => 'Ido','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '646','name' => 'Irepo','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '647','name' => 'Iseyin','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '648','name' => 'Itesiwaju','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '649','name' => 'Iwajowa','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '650','name' => 'Kajola','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '651','name' => 'Lagelu','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '652','name' => 'Ogbomosho North','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '653','name' => 'Ogbomosho South','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '654','name' => 'Ogo Oluwa','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '655','name' => 'Olorunsogo','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '656','name' => 'Oluyole','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '657','name' => 'Ona Ara','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '658','name' => 'Orelope','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '659','name' => 'Ori Ire','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '660','name' => 'Oyo','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '661','name' => 'Oyo East','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '662','name' => 'Saki East','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '663','name' => 'Saki West','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '664','name' => 'Surulere, Oyo State','code' => '','state_id' => '31','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '665','name' => 'Bokkos','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '666','name' => 'Barkin Ladi','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '667','name' => 'Bassa','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '668','name' => 'Jos East','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '669','name' => 'Jos North','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '670','name' => 'Jos South','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '671','name' => 'Kanam','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '672','name' => 'Kanke','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '673','name' => 'Langtang South','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '674','name' => 'Langtang North','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '675','name' => 'Mangu','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '676','name' => 'Mikang','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '677','name' => 'Pankshin','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '678','name' => 'Qua\'an Pan','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '679','name' => 'Riyom','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '680','name' => 'Shendam','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '681','name' => 'Wase','code' => '','state_id' => '32','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '682','name' => 'Abua/Odual','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '683','name' => 'Ahoada East','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '684','name' => 'Ahoada West','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '685','name' => 'Akuku-Toru','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '686','name' => 'Andoni','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '687','name' => 'Asari-Toru','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '688','name' => 'Bonny','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '689','name' => 'Degema','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '690','name' => 'Eleme','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '691','name' => 'Emuoha','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '692','name' => 'Etche','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '693','name' => 'Gokana','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '694','name' => 'Ikwerre','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '695','name' => 'Khana','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '696','name' => 'Obio/Akpor','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '697','name' => 'Ogba/Egbema/Ndoni','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '698','name' => 'Ogu/Bolo','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '699','name' => 'Okrika','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '700','name' => 'Omuma','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '701','name' => 'Opobo/Nkoro','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '702','name' => 'Oyigbo','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '703','name' => 'Port Harcourt','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '704','name' => 'Tai','code' => '','state_id' => '33','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '705','name' => 'Binji','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '706','name' => 'Bodinga','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '707','name' => 'Dange Shuni','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '708','name' => 'Gada','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '709','name' => 'Goronyo','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '710','name' => 'Gudu','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '711','name' => 'Gwadabawa','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '712','name' => 'Illela','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '713','name' => 'Isa','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '714','name' => 'Kebbe','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '715','name' => 'Kware','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '716','name' => 'Rabah','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '717','name' => 'Sabon Birni','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '718','name' => 'Shagari','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '719','name' => 'Silame','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '720','name' => 'Sokoto North','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '721','name' => 'Sokoto South','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '722','name' => 'Tambuwal','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '723','name' => 'Tangaza','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '724','name' => 'Tureta','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '725','name' => 'Wamako','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '726','name' => 'Wurno','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '727','name' => 'Yabo','code' => '','state_id' => '34','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '728','name' => 'Ardo Kola','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '729','name' => 'Bali','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '730','name' => 'Donga','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '731','name' => 'Gashaka','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '732','name' => 'Gassol','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '733','name' => 'Ibi','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '734','name' => 'Jalingo','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '735','name' => 'Karim Lamido','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '736','name' => 'Kumi','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '737','name' => 'Lau','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '738','name' => 'Sardauna','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '739','name' => 'Takum','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '740','name' => 'Ussa','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '741','name' => 'Wukari','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '742','name' => 'Yorro','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '743','name' => 'Zing','code' => '','state_id' => '35','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '744','name' => 'Bade','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '745','name' => 'Bursari','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '746','name' => 'Damaturu','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '747','name' => 'Fika','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '748','name' => 'Fune','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '749','name' => 'Geidam','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '750','name' => 'Gujba','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '751','name' => 'Gulani','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '752','name' => 'Jakusko','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '753','name' => 'Karasuwa','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '754','name' => 'Machina','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '755','name' => 'Nangere','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '756','name' => 'Nguru','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '757','name' => 'Potiskum','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '758','name' => 'Tarmuwa','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '759','name' => 'Yunusari','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '760','name' => 'Yusufari','code' => '','state_id' => '36','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '761','name' => 'Anka','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '762','name' => 'Bakura','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '763','name' => 'Birnin Magaji/Kiyaw','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '764','name' => 'Bukkuyum','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '765','name' => 'Bungudu','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '766','name' => 'Gummi','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '767','name' => 'Gusau','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '768','name' => 'Kaura Namoda','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '769','name' => 'Maradun','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '770','name' => 'Maru','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '771','name' => 'Shinkafi','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '772','name' => 'Talata Mafara','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '773','name' => 'Tsafe','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => ''),
  array('id' => '774','name' => 'Zurmi','code' => '','state_id' => '37','state_zone_id' => '0','code_pattern' => '')
);


  foreach($cities  as $key => $val)
  {
    DB::table('cities')->updateOrInsert(
      [
          'city_name' => $val['name'],   // condition
          'state_id'  => $val['state_id']
      ],
      [
          'city_name' => $val['name'],   // values to insert/update
          'state_id'  => $val['state_id']
      ]
    );
  }
    
 }
}
